### ISSUE TITLE
Spigot max-tick-time limit doesn't work

### ISSUE THREAD

**Issue by meytro** [PaperSpigot/Paper-1.7#51]
I don't really know why but since I use PaperSpigot the max-tick-time limit doesn't work anymore. I set the max-tick-time for entities to 10 but  it still goes up to 13 (up to 23 if you count in the tracker and not activated entities).

Does somebody have a solution for this? I really need this limit!

**Comment by Byteflux** [comment]
This patch was removed in PaperSpigot because it breaks TNT cannons.

**Comment by meytro** [comment]
Maybe you could add a option to enable this limits again even if TNT cannons break through it? I lead a large non-pvp Skyblock server so there is no point to abstain the feature for TNT cannons which aren't used.

I would really appreciate it if you could bring it back!

**Comment by Byteflux** [comment]
Maybe, but right now PaperSpigot is used more on Factions servers which needs TNT cannons to not break. If we figure out a way to make the option exist without breaking cannons, we'll readd it.

**Comment by meytro** [comment]
As that: Would be really nice if you find a solution for it. I don't want to switch back to Spigot without the lava/water optimizations ;)

**Comment by Ichbinjoe** [comment]
I will look into this to see if I can't figure something out.

**Comment by Ichbinjoe** [comment]
I think this all can be achieved with a Boolean flag. I will create a pull soon.

**Comment by meytro** [comment]
When I compiled the newest version a few seconds ago I saw this:
"Allow Capping (Tile)Entity Tick Time."
Is this patch for the issue which I created here? Can't test it at the moment, sorry for asking.

**Comment by Byteflux** [comment]
Yes that is Spigot's patch which breaks cannoning. PaperSpigot removed that patch.

**Comment by meytro** [comment]
Ah ok, I thought it would fix that and adds a Boolean flag to toggle the feature. Missunderstanding, thanks for clarification.

**Comment by meytro** [comment]
Any updates on this?

**Comment by Zbob750** [comment]
We've seen a few possible implementations based on this but haven't tested any of them in detail. This will likely make its way into 1.8.8 (or beyond) at some point in the future, however 1.7.10 is dead and will not be seeing this (at least from us).

**Comment by madtomic** [comment]
You guys not updating 1.7 anymore? Noooo 😔😔😔😔

**Comment by Zbob750** [comment]
It's on the main page in the readme, it was time to move on.
