### ISSUE TITLE
Ability to toggle "Teleport the vehicle and the passenger"

### ISSUE THREAD

**Issue by CH4MPION98** [PaperSpigot/Paper-1.7#53]
Hello,

First and foremost, thank you for your frequent updates to PaperSpigot - I recently switched from the normal Spigot version and I have been stunned by the improvements and stability that you are able to offer!

However, one area which I would really like adjusting is the way in which PaperSpigot allows:

Teleporting the vehicle and the passenger - ie teleporting with horses, boats et cetera. 

This changes gameplay and so I would really appreciate an option offered in the paper.yml file which allows this to be toggled.

Many thanks in advance for reading this!

**Comment by caoli5288** [comment]
think so.

**Comment by Ichbinjoe** [comment]
See, the issue I see with this is that any teleportations performed by plugins would then also take the 'vehicle', which may not be preferred. We can check to see if its a portal teleportation and maybe include that check with configurations. Ex. Configuration to only teleport vehicle with rider when going through a portal, as well as a blanket configuration to teleport the vehicle with rider always. I guess another question is this: Do we teleport the rider with the vehicle or the vehicle with the rider... (a question of what triggers it). Or is that configurable :P the sky is the limit right now. Another issue I see: both go into a portal, and assuming the rider teleport triggers the successive vehicle teleport, and the vehicle teleports within the same tick before the rider... the rider would then be unmounted breaking this mechanic.

**Comment by CH4MPION98** [comment]
Thanks for the swift response!

I'd personally like to see a a blanket configuration to teleport the vehicle with rider always.

This would allow operators to choose between allowing vehicles to be teleported with players or not.

In our case, we allow players with a certain assigned permission to teleport with horses - the problem being that PaperSpigot allows teleportation with vehicles by default. 

Would it be possible to implement such a toggle feature in the configuration? It would be very much appreciated!

**Comment by Ichbinjoe** [comment]
So would you want something in the PlayerTeleportationEvent (or whatever its called, don't know it off the top of my head) like a flag to enable or disable teleporting the vehicles with the rider, or would you want something else? @CH4MPION98

**Comment by Techcable** [comment]
@Ichbinjoe 
Nope, a global flag to disable.
Then if they want to preseve mounts they can do something like this:
https://github.com/TechzoneMC/TechUtils/blob/master/src/main/java/net/techcable/techutils/entity/TechPlayer.java#L130-L144

**Comment by CH4MPION98** [comment]
Thank you again for getting back to me!

Personally, I would like to see a global flag to disable teleporting with vehicles in the paper.yml.

This would still allow the ability to allow teleportation with vehicles using plugin code with Spigot/Bukkit API, but would prevent all players being able to teleport vehicles by default.

**Comment by Log1x** [comment]
This would be great!!

**Comment by CH4MPION98** [comment]
I'd hate to pressure you but is there any news on this?

Been 28 days since I initially posted it.

**Comment by Zbob750** [comment]
Does vehicle teleportation even work with 1.8.8? I seem to remember there being some trouble with it.
If so, then yes, we will be adding this feature relatively soon. I'll have to double check it.

If it doesn't work on 1.8.x and only works on 1.7, then no. 1.7.10 is no longer supported. If someone else wants to fork and add it this they certainly could, it shouldn't be all that complicated.
