### ISSUE TITLE
To resume construction of version 1.7.10!

### ISSUE THREAD

**Issue by FunnyCraft** [PaperSpigot/Paper-1.7#57]
+ You have a problem with the plugin here Authme not link him http://dev.bukkit.org/bukkit-plugins/authme-reloaded/, the problem is the fact that when logged in after a few minutes or an hour can log out ... The problem I see is only on your build.

**Comment by Zbob750** [comment]
We don't support this version any longer. If it's still present on 1.8 we'll look into it, but 1.7 is not supported.
