### ISSUE TITLE
40 TPS for combat

### ISSUE THREAD

**Issue by HunterGPlays** [PaperSpigot/Paper-1.7#59]
I saw the thing where Vax's servers run at 40 tps, but it only affect's player combat/movement.
https://www.spigotmc.org/threads/over-20-tps.95756/

Any thoughts?

**Comment by Zbob750** [comment]
The "science" behind the vast majority of true 40 TPS implementations is sketchy and, in most cases, is mostly unnoticeable by players. Notice I said "true 40 TPS implementations", as there are several server implementations that just lie about their TPS, and several servers which do the same.

Regardless, we have no interest in adding such a feature to Paper.
