### ISSUE TITLE
Server stops responding

### ISSUE THREAD

**Issue by ASCIIcat** [PaperSpigot/Paper-1.7#63]
This is happening on the latest build about every few hours, have tried rebuilding the paper-spigot.jar
http://pastebin.com/BX2Udz8G

I am not quite sure what could be causing it

**Comment by Byteflux** [comment]
You are using a poorly written plugin. This is not a PaperSpigot bug.

------------------------------
Server thread dump (Look for plugins here before reporting to PaperSpigot!):
------------------------------
Current Thread: Server thread
        PID: 16 | Suspended: false | Native: true | State: RUNNABLE
        Stack:
                java.net.SocketInputStream.socketRead0(Native Method)
                java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
                java.net.SocketInputStream.read(SocketInputStream.java:170)
                java.net.SocketInputStream.read(SocketInputStream.java:141)
                sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
                sun.security.ssl.InputRecord.readV3Record(InputRecord.java:593)
                sun.security.ssl.InputRecord.read(InputRecord.java:532)
                sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
                sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
                sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
                sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
                sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
                sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
                sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
                **me.leoko.ban.main.getUUID(main.java:938)**
                **me.leoko.ban.Events.onJoin(Events.java:51)**
                sun.reflect.GeneratedMethodAccessor243.invoke(Unknown Source)
                sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                java.lang.reflect.Method.invoke(Method.java:497)
                org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
                org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
                me.Incomprehendable.WorldPlugins.FakePluginManager.fireEvent(FakePluginManager.java:138)
                me.Incomprehendable.WorldPlugins.FakePluginManager.callEvent(FakePluginManager.java:124)
                net.minecraft.server.v1_8_R3.LoginListener$LoginHandler$1.evaluate(LoginListener.java:258)
                net.minecraft.server.v1_8_R3.LoginListener$LoginHandler$1.evaluate(LoginListener.java:1)
                org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24)
                net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786)
                net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
                net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:711)
                net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:614)
                java.lang.Thread.run(Thread.java:745)
